#Tell Spring where to get the data from
server:
    port: 8082
    
spring:
  application:
    name: budget-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/budget_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: update

    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 30
    hostname: ${AWS_HOSTNAME:localhost}

exchanges:
  direct: direct-exchange

queues:
  budget:
    request: budget-request