#Tell Spring where to get the data from
server:
    port: 8082
    
spring:
  application:
    name: budget-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/budget_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: update

    show-sql: true

  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 30

# creating the rabbitmq fanout exchange
exchanges:
  fanout: delete-user

queues:
  fanout:
    budgetService: deleteUserQueueBudgets
    bucketService: deleteUserQueueBuckets

# creating the routing key for the exchange
routing-key: key1234
